In [2]:
import numpy as np
import xarray as xr


In [55]:
rng = np.random.default_rng(42)

In [56]:
# 5 variables, 200 observaciones
X = xr.DataArray(
    rng.normal(loc = 1, scale = 0.1, size = (200, 5)),
    dims = ("obs", "var"),
    coords = {"obs": np.arange(200), "var": [f"x_{i}" for i in np.arange(1, 6)]}
)
X

<xarray.DataArray (obs: 200, var: 5)>
array([[1.03047171, 0.89600159, 1.07504512, 1.09405647, 0.80489648],
       [0.86978205, 1.01278404, 0.96837574, 0.99831988, 0.91469561],
       [1.0879398 , 1.07777919, 1.00660307, 1.11272412, 1.04675093],
       [0.91407075, 1.03687508, 0.90411174, 1.08784503, 0.99500741],
       [0.98151376, 0.93190705, 1.12225413, 0.98454705, 0.95716722],
       [0.96478664, 1.05323092, 1.03654441, 1.04127326, 1.0430821 ],
       [1.21416476, 0.9593585 , 0.94877573, 0.91862273, 1.06159794],
       [1.11289723, 0.98860525, 0.91598435, 0.91755188, 1.06505928],
       [1.07432542, 1.05431543, 0.93344903, 1.02321613, 1.01166858],
       [1.02186886, 1.08714288, 1.02235955, 1.06789136, 1.00675791],
       [1.02891194, 1.06312882, 0.85428442, 0.96803288, 0.95296273],
       [0.93611222, 0.97248577, 1.14949413, 0.91341689, 1.09682784],
       [0.83171302, 0.9665115 , 1.01627531, 1.05862223, 1.07112266],
       [1.07933472, 0.96512749, 0.95376482, 1.08579759, 0.98086957],
       [0.87243137, 0.88667128, 0.90805477, 1.04971607, 1.01424257],
       [1.06904854, 0.95727474, 1.01585397, 1.06255904, 0.96906535],
       [1.04567752, 0.93380741, 0.96369462, 0.96182621, 0.88041604],
       [1.04869725, 0.95305977, 1.00124941, 1.04807467, 1.04465312],
       [1.06653851, 0.99015145, 0.95767017, 0.99202818, 0.83126656],
       [0.85528875, 0.86773004, 0.90027532, 1.03997742, 0.90945209],
...
       [1.03896917, 1.01025532, 0.98525575, 1.15882761, 0.93777926],
       [1.20602982, 0.97745686, 0.87229836, 1.00699196, 0.89237548],
       [0.92482442, 1.03970333, 1.05555821, 0.93778323, 1.09874051],
       [1.11575078, 1.14363018, 1.05294134, 1.13634287, 0.81192016],
       [0.96820935, 0.91329947, 1.01192259, 0.94285508, 0.98338422],
       [1.18821749, 0.98302802, 1.04137923, 0.97677307, 1.00757133],
       [1.00060167, 1.04483241, 1.11653075, 1.1647394 , 1.03096201],
       [1.05895469, 0.88491355, 0.99121233, 1.09402895, 1.08659686],
       [1.02116097, 1.0886394 , 1.04907667, 1.12003063, 1.02893592],
       [0.96443017, 1.03358413, 0.70694056, 1.03828857, 0.63515872],
       [0.82765366, 1.04517686, 1.04775293, 0.88375712, 0.9287898 ],
       [1.1370541 , 0.95159699, 1.22429203, 0.99980801, 1.04080362],
       [1.16168744, 1.01310271, 0.8997656 , 0.98902725, 0.99643893],
       [0.86352583, 0.97441679, 0.92578079, 1.09243578, 1.00346119],
       [0.97172043, 0.98938181, 1.0223122 , 1.06168142, 0.90002878],
       [0.89584124, 1.11046792, 0.95876631, 0.85831579, 1.04438127],
       [1.04633698, 0.84692847, 1.02294817, 1.07355831, 1.03743865],
       [1.06319815, 0.85957309, 1.03310402, 0.96973802, 0.95172098],
       [1.08705556, 1.14792745, 1.17943701, 1.13148079, 0.98902658],
       [1.03527202, 1.07668229, 1.01211779, 1.01307642, 1.08237531]])
Coordinates:
  * obs      (obs) int32 0 1 2 3 4 5 6 7 8 ... 192 193 194 195 196 197 198 199
  * var      (var) <U3 'x_1' 'x_2' 'x_3' 'x_4' 'x_5'

In [64]:
Betas = xr.DataArray(
    rng.normal(loc = 0, scale = 0.1, size = (5, 1)),
    dims = ("var", "coef"),
    coords = {"var": [f"beta_{i}" for i in np.arange(1, 6)], "coef": ["beta"]}
)
Betas

<xarray.DataArray (var: 5, coef: 1)>
array([[-0.08521588],
       [ 0.22292736],
       [ 0.09954903],
       [ 0.0971139 ],
       [ 0.00280222]])
Coordinates:
  * var      (var) <U6 'beta_1' 'beta_2' 'beta_3' 'beta_4' 'beta_5'
  * coef     (coef) <U4 'beta'

In [65]:

Y = X @ Betas + rng.normal(loc = 0, scale = 0.1, size = (200, 1))

Y

<xarray.DataArray (obs: 200, coef: 1)>
array([[-0.02172262],
       [-0.02094088],
       [ 0.03905306],
       [ 0.14011863],
       [ 0.01813142],
       [-0.09114436],
       [ 0.08244271],
       [ 0.09211507],
       [ 0.06546595],
       [ 0.07454989],
       [-0.02709281],
       [-0.09289892],
       [-0.08681934],
       [-0.16354632],
       [ 0.02369486],
       [-0.00834488],
       [-0.04399877],
       [-0.29556188],
       [-0.12473175],
       [ 0.11208407],
...
       [-0.00549349],
       [ 0.11326898],
       [ 0.12645398],
       [-0.14217636],
       [-0.03123554],
       [ 0.13581211],
       [ 0.05080791],
       [ 0.0195263 ],
       [-0.02176847],
       [-0.03838009],
       [ 0.02882191],
       [-0.02523741],
       [-0.00425786],
       [ 0.00785987],
       [-0.06780715],
       [ 0.05321294],
       [ 0.29142446],
       [-0.17769866],
       [ 0.03240125],
       [-0.07601901]])
Coordinates:
  * obs      (obs) int32 0 1 2 3 4 5 6 7 8 ... 192 193 194 195 196 197 198 199
  * coef     (coef) <U4 'beta'