In [2]:
import numpy as np
import xarray as xr


In [55]:
rng = np.random.default_rng(42)

In [56]:
# 5 variables, 200 observaciones
X = xr.DataArray(
    rng.normal(loc = 1, scale = 0.1, size = (200, 5)),
    dims = ("obs", "var"),
    coords = {"obs": np.arange(200), "var": [f"x_{i}" for i in np.arange(1, 6)]}
)
X

<xarray.DataArray (obs: 200, var: 5)>
array([[1.03047171, 0.89600159, 1.07504512, 1.09405647, 0.80489648],
       [0.86978205, 1.01278404, 0.96837574, 0.99831988, 0.91469561],
       [1.0879398 , 1.07777919, 1.00660307, 1.11272412, 1.04675093],
       [0.91407075, 1.03687508, 0.90411174, 1.08784503, 0.99500741],
       [0.98151376, 0.93190705, 1.12225413, 0.98454705, 0.95716722],
       [0.96478664, 1.05323092, 1.03654441, 1.04127326, 1.0430821 ],
       [1.21416476, 0.9593585 , 0.94877573, 0.91862273, 1.06159794],
       [1.11289723, 0.98860525, 0.91598435, 0.91755188, 1.06505928],
       [1.07432542, 1.05431543, 0.93344903, 1.02321613, 1.01166858],
       [1.02186886, 1.08714288, 1.02235955, 1.06789136, 1.00675791],
       [1.02891194, 1.06312882, 0.85428442, 0.96803288, 0.95296273],
       [0.93611222, 0.97248577, 1.14949413, 0.91341689, 1.09682784],
       [0.83171302, 0.9665115 , 1.01627531, 1.05862223, 1.07112266],
       [1.07933472, 0.96512749, 0.95376482, 1.08579759, 0.98086957],
       [0.87243137, 0.88667128, 0.90805477, 1.04971607, 1.01424257],
       [1.06904854, 0.95727474, 1.01585397, 1.06255904, 0.96906535],
       [1.04567752, 0.93380741, 0.96369462, 0.96182621, 0.88041604],
       [1.04869725, 0.95305977, 1.00124941, 1.04807467, 1.04465312],
       [1.06653851, 0.99015145, 0.95767017, 0.99202818, 0.83126656],
       [0.85528875, 0.86773004, 0.90027532, 1.03997742, 0.90945209],
...
       [1.03896917, 1.01025532, 0.98525575, 1.15882761, 0.93777926],
       [1.20602982, 0.97745686, 0.87229836, 1.00699196, 0.89237548],
       [0.92482442, 1.03970333, 1.05555821, 0.93778323, 1.09874051],
       [1.11575078, 1.14363018, 1.05294134, 1.13634287, 0.81192016],
       [0.96820935, 0.91329947, 1.01192259, 0.94285508, 0.98338422],
       [1.18821749, 0.98302802, 1.04137923, 0.97677307, 1.00757133],
       [1.00060167, 1.04483241, 1.11653075, 1.1647394 , 1.03096201],
       [1.05895469, 0.88491355, 0.99121233, 1.09402895, 1.08659686],
       [1.02116097, 1.0886394 , 1.04907667, 1.12003063, 1.02893592],
       [0.96443017, 1.03358413, 0.70694056, 1.03828857, 0.63515872],
       [0.82765366, 1.04517686, 1.04775293, 0.88375712, 0.9287898 ],
       [1.1370541 , 0.95159699, 1.22429203, 0.99980801, 1.04080362],
       [1.16168744, 1.01310271, 0.8997656 , 0.98902725, 0.99643893],
       [0.86352583, 0.97441679, 0.92578079, 1.09243578, 1.00346119],
       [0.97172043, 0.98938181, 1.0223122 , 1.06168142, 0.90002878],
       [0.89584124, 1.11046792, 0.95876631, 0.85831579, 1.04438127],
       [1.04633698, 0.84692847, 1.02294817, 1.07355831, 1.03743865],
       [1.06319815, 0.85957309, 1.03310402, 0.96973802, 0.95172098],
       [1.08705556, 1.14792745, 1.17943701, 1.13148079, 0.98902658],
       [1.03527202, 1.07668229, 1.01211779, 1.01307642, 1.08237531]])
Coordinates:
  * obs      (obs) int32 0 1 2 3 4 5 6 7 8 ... 192 193 194 195 196 197 198 199
  * var      (var) <U3 'x_1' 'x_2' 'x_3' 'x_4' 'x_5'

In [64]:
Betas = xr.DataArray(
    rng.normal(loc = 0, scale = 0.1, size = (5, 1)),
    dims = ("var", "coef"),
    coords = {"var": [f"beta_{i}" for i in np.arange(1, 6)], "coef": ["beta"]}
)
Betas

<xarray.DataArray (var: 5, coef: 1)>
array([[-0.08521588],
       [ 0.22292736],
       [ 0.09954903],
       [ 0.0971139 ],
       [ 0.00280222]])
Coordinates:
  * var      (var) <U6 'beta_1' 'beta_2' 'beta_3' 'beta_4' 'beta_5'
  * coef     (coef) <U4 'beta'

In [65]:

Y = X @ Betas + rng.normal(loc = 0, scale = 0.1, size = (200, 1))

Y

<xarray.DataArray (obs: 200, coef: 1)>
array([[-0.02172262],
       [-0.02094088],
       [ 0.03905306],
       [ 0.14011863],
       [ 0.01813142],
       [-0.09114436],
       [ 0.08244271],
       [ 0.09211507],
       [ 0.06546595],
       [ 0.07454989],
       [-0.02709281],
       [-0.09289892],
       [-0.08681934],
       [-0.16354632],
       [ 0.02369486],
       [-0.00834488],
       [-0.04399877],
       [-0.29556188],
       [-0.12473175],
       [ 0.11208407],
...
       [-0.00549349],
       [ 0.11326898],
       [ 0.12645398],
       [-0.14217636],
       [-0.03123554],
       [ 0.13581211],
       [ 0.05080791],
       [ 0.0195263 ],
       [-0.02176847],
       [-0.03838009],
       [ 0.02882191],
       [-0.02523741],
       [-0.00425786],
       [ 0.00785987],
       [-0.06780715],
       [ 0.05321294],
       [ 0.29142446],
       [-0.17769866],
       [ 0.03240125],
       [-0.07601901]])
Coordinates:
  * obs      (obs) int32 0 1 2 3 4 5 6 7 8 ... 192 193 194 195 196 197 198 199
  * coef     (coef) <U4 'beta'

# Índice del Minicurso sobre xarray

1. Introducción a xarray

+ ¿Qué es xarray y para qué se utiliza?
+ Diferencias y similitudes con NumPy y pandas.

2. Estructuras de Datos en xarray

+ DataArray: El contenedor multidimensional.
+ Dataset: Contenedor para múltiples DataArrays.

3. Creando Arrays y Datasets

+ Crear DataArrays desde cero.
+ Cargar datos desde archivos (ej. netCDF, HDF).

4. Indexación y Selección

+ Básica: Similar a NumPy.
+ Avanzada: Uso de etiquetas y nombres de dimensiones.

5. Trabajando con Dimensiones

+ Entender y trabajar con dimensiones nombradas.
+ Alineación automática basada en etiquetas.

6. Cálculos y Operaciones

+ Cálculos matemáticos y estadísticos.
+ Operaciones de reducción y agrupación.

7. Trabajar con Datos Faltantes

+ Identificar y manejar datos faltantes.
+ Interpolación y llenado de datos.

8. Visualización

+ Gráficos integrados con Matplotlib.
+ Personalización y trucos para visualizaciones avanzadas.

9. Trabajando con Series Temporales

+ Funcionalidades específicas para datos temporales.
+ Resampleado, agrupamiento y análisis de series temporales.

10. Aplicaciones Avanzadas

+ Ejemplo: Análisis de datos climáticos.
+ Integración con otras bibliotecas (Dask, SciPy, etc.)

11. Mejores Prácticas y Consejos

+ Manejo eficiente de la memoria.
+ Consejos para trabajar con grandes datasets.

12. Recursos y Comunidad

+ Dónde encontrar ayuda.
+ Contribuir a xarray.

# Introducción a xarray

## ¿Qué es xarray y para qué se utiliza?

xarray es una biblioteca de Python de código abierto que facilita el trabajo con arrays multidimensionales etiquetados y datos tipo tabla. Está construida sobre NumPy y pandas, proporcionando una potente interfaz para modelar, transformar y analizar datos con dimensiones nombradas y coordenadas. Es especialmente útil en campos donde los datos suelen ser multidimensionales por naturaleza, como la meteorología, la oceanografía, la climatología, y la física.

**Principales usos de xarray**:

+ Análisis de Datos Multidimensionales: xarray simplifica el manejo de datos donde cada dimensión también puede tener etiquetas o coordenadas, como tiempo, latitud, longitud, y niveles de presión.
+ Datos Tipo Tabla y Series Temporales: Además de datos multidimensionales, xarray maneja bien series temporales y datos tipo tabla, especialmente cuando se manejan múltiples series temporales con diferentes coordenadas temporales.
+ Integración con Herramientas Científicas: Funciona bien con otras bibliotecas científicas y de datos, permitiendo análisis complejos y operaciones de alto rendimiento con facilidad.


## Diferencias y similitudes con NumPy y pandas.

Con NumPy:

Similitudes:

+ Ambos están basados en arrays. xarray usa 'DataArray', que es una extensión de los arrays de NumPy.
+ Ofrecen capacidades similares para operaciones matemáticas y lógicas básicas.

Diferencias:

+ Dimensiones Nombradas y Coordenadas: xarray permite nombrar las dimensiones y asignar coordenadas, lo que hace que trabajar con datos sea más intuitivo y menos propenso a errores.
+ Operaciones basadas en etiquetas: Mientras que NumPy opera basándose en índices numéricos, xarray permite el uso de etiquetas para acceder y manipular datos.
+ Manejo de Datos Faltantes: xarray tiene una mejor integración con pandas para manejar datos faltantes de manera más eficiente.

Con pandas:

Similitudes:

+ Ambos manejan datos etiquetados y ofrecen funciones potentes para manipulación y análisis de datos.
+ Tienen operaciones de agrupación, filtrado, y combinación similares.

Diferencias:

+ Multidimensionalidad: Mientras que pandas es excelente para trabajar con datos 1D (Series) y 2D (DataFrame), xarray brilla con datos de 3D en adelante, gestionando múltiples dimensiones de manera más efectiva.
+ Series Temporales y Datos Espaciales: xarray está específicamente diseñado para trabajar bien con series temporales y datos espaciales, una necesidad común en la ciencia del clima y la oceanografía.
+ Integración con NumPy: xarray extiende y utiliza NumPy, lo que lo hace naturalmente compatible con el ecosistema científico de Python.


En resumen, xarray toma lo mejor de NumPy y pandas y lo extiende para trabajar de manera más efectiva con datos multidimensionales, etiquetados y complejos. Es una herramienta invaluable para científicos y analistas que trabajan en campos donde los datos son inherentemente multidimensionales y necesitan una herramienta potente y flexible para análisis y visualización.

# Estructuras de Datos en xarray

xarray introduce principalmente dos tipos de estructuras de datos: DataArray y Dataset, cada una con características y usos específicos que las hacen potentes herramientas para el análisis de datos multidimensionales.

## DataArray: El contenedor multidimensional.

¿Qué es un DataArray?

+ Un DataArray es la estructura de datos central de xarray, diseñada para manejar arrays multidimensionales con etiquetas.
+ Cada DataArray tiene cuatro partes esenciales:
    1. Datos: Un array NumPy o Dask que contiene los valores.
    2. Dimensiones: Nombres para cada eje del array. Por ejemplo, en datos climáticos, podrías tener dimensiones como 'tiempo', 'latitud', y 'longitud'.
    3. Coordenadas: Arrays que etiquetan cada punto en las dimensiones, como fechas específicas para 'tiempo' o valores de latitud/longitud para 'espacio'.
    4. Atributos: Un diccionario para almacenar metadatos arbitrarios, como la unidad de medida o el nombre del dataset.

Características y Usos de DataArray

+ Etiquetas y Coordenadas: Puedes usar etiquetas en lugar de índices numéricos para orientarte y acceder a los datos, lo que reduce los errores y hace que el código sea más legible.
+ Operaciones Matemáticas: Soporta operaciones aritméticas directas y alineación automática de datos basada en coordenadas.
+ Facilidad de Uso: Integración con pandas y NumPy hace que sea fácil convertir entre estructuras de datos y aplicar operaciones matemáticas y lógicas.
+ Visualización Integrada: Viene con métodos de trazado incorporados basados en Matplotlib para visualizar datos rápidamente.


## Dataset: Contenedor para múltiples DataArrays.

¿Qué es un Dataset?

+ Un Dataset es una colección de DataArrays que comparten las mismas dimensiones y coordenadas, similar a cómo un DataFrame en pandas puede contener múltiples Series.
+ Piensa en Dataset como un dictado multidimensional de arrays con etiquetas, donde cada array (DataArray) es una variable con su propio nombre, datos y dimensiones.

Componentes de un Dataset:

+ Variables: Un conjunto de DataArray, cada uno con un nombre único.
+ Dimensiones: Nombres para cada eje en el Dataset, compartidos entre las variables.
+ Coordenadas: Arrays que etiquetan cada punto en las dimensiones, comunes a todas las variables.
+ Atributos: Metadatos generales del Dataset.

Características y Usos de Dataset

+ Manejo de Variables Múltiples: Ideal para trabajar con archivos de datos complejos donde cada variable puede tener diferentes dimensiones.
+ Operaciones Conjuntas: Realiza operaciones matemáticas y lógicas en todas las variables simultáneamente, manteniendo la alineación basada en coordenadas.
+ Fácil Subconjunto y Manipulación: Selecciona, corta y manipula datos de múltiples variables de manera eficiente.
+ Entrada/Salida Eficaz: Carga y guarda datos de una amplia variedad de formatos, incluyendo netCDF, que es un estándar en ciencias atmosféricas y oceánicas.

Conclusión

DataArray y Dataset son estructuras poderosas y flexibles que hacen que xarray sea una herramienta esencial para el análisis de datos multidimensionales. Permiten un manejo intuitivo y eficiente de datos complejos, ofrecen operaciones aritméticas y lógicas simplificadas, y facilitan la visualización y manipulación avanzada de datos. En las siguientes secciones, exploraremos cómo crear y manipular estas estructuras para realizar análisis efectivos y eficientes.

# Creando Arrays y Datasets

Vamos a explorar cómo puedes comenzar a trabajar con xarray creando DataArray y Dataset desde cero y cómo cargar datos desde archivos comunes en ciencia de datos y meteorología.

## Crear DataArrays desde cero.

In [66]:
## 1.  Importando xarray:
#  Primero, necesitas importar xarray. La convención común es importarlo como xr.
import xarray as xr
import numpy as np

## 2. Creando un DataArray Simple:
#  Puedes crear un DataArray directamente desde un array de NumPy o una lista de 
#  Python, especificando opcionalmente dimensiones y coordenadas.

# Creando datos aleatorios
data = np.random.rand(4, 3)

# Creando un DataArray sin coordenadas
da_simple = xr.DataArray(data)
print(da_simple)

<xarray.DataArray (dim_0: 4, dim_1: 3)>
array([[0.9890209 , 0.37213723, 0.86809711],
       [0.12744124, 0.93129416, 0.5264298 ],
       [0.88364454, 0.4498944 , 0.2775394 ],
       [0.50185313, 0.33229598, 0.19563442]])
Dimensions without coordinates: dim_0, dim_1


In [67]:
## 3. Especificando Dimensiones y Coordenadas:
#  Para aprovechar plenamente las capacidades de xarray, define las dimensiones 
#  y coordenadas de tus datos.

# Nombres de dimensiones
dims = ['x', 'y']

# Coordenadas
coords = {'x': [10, 20, 30, 40], 'y': [1, 2, 3]}

# Creando el DataArray
da = xr.DataArray(data, dims=dims, coords=coords)
print(da)


<xarray.DataArray (x: 4, y: 3)>
array([[0.9890209 , 0.37213723, 0.86809711],
       [0.12744124, 0.93129416, 0.5264298 ],
       [0.88364454, 0.4498944 , 0.2775394 ],
       [0.50185313, 0.33229598, 0.19563442]])
Coordinates:
  * x        (x) int32 10 20 30 40
  * y        (y) int32 1 2 3


## Crear Datasets desde cero

In [68]:
## 1. Creando un Dataset Vacío:
# Puedes comenzar con un Dataset vacío y luego agregarle DataArray.
ds = xr.Dataset()
print(ds)

<xarray.Dataset>
Dimensions:  ()
Data variables:
    *empty*


In [69]:
## Añadiendo DataArrays:
# Agrega DataArray como variables al Dataset. Cada DataArray puede tener 
# diferentes dimensiones y coordenadas, pero xarray alineará automáticamente las
# dimensiones comunes.
# Añadiendo el primer DataArray
ds['temp'] = da

# Añadiendo otro DataArray
ds['pressure'] = xr.DataArray(np.random.rand(4), dims='x')
print(ds)


<xarray.Dataset>
Dimensions:   (x: 4, y: 3)
Coordinates:
  * x         (x) int32 10 20 30 40
  * y         (y) int32 1 2 3
Data variables:
    temp      (x, y) float64 0.989 0.3721 0.8681 0.1274 ... 0.5019 0.3323 0.1956
    pressure  (x) float64 0.3117 0.3345 0.9708 0.776


## Cargar datos desde archivos (ej. netCDF, HDF).

xarray soporta la lectura y escritura de varios formatos de datos, pero los más comunes en ciencia de datos y meteorología son netCDF y HDF.

El formato netCDF es un formato estándar y muy utilizado en la comunidad científica, especialmente para datos climáticos, oceanográficos y meteorológicos.

In [ ]:
# 1. Guardar un Dataset como archivo netCDF:

ds.to_netcdf('../../../data/clean/my_dataset.nc')

# 2. Opciones Avanzadas:
# Puedes especificar modos de escritura, formatos y opciones de compresión:
ds.to_netcdf(
    '../../../data/clean/my_dataset.nc', 
    mode='w', # Sobrescribe el archivo si ya existe
    format='NETCDF4', # Especifica el formato netCDF; otros incluyen 'NETCDF3_64BIT', etc.
    compression={'var': dict(zlib=True, complevel=5)} # Un diccionario especificando opciones de compresión para las variables.
    )


In [74]:
# 3. Cargar desde un archivo netCDF:

# Reemplaza 'path_to_file.nc' con la ruta real de tu archivo netCDF
ds_from_netcdf = xr.open_dataset('../../../data/clean/my_dataset.nc')
print(ds_from_netcdf)

<xarray.Dataset>
Dimensions:   (x: 4, y: 3)
Coordinates:
  * x         (x) int32 10 20 30 40
  * y         (y) int32 1 2 3
Data variables:
    temp      (x, y) float64 ...
    pressure  (x) float64 ...


In [78]:
# 4. Convertir un Dataset a HDF:
import h5py

# Convierte el Dataset de xarray a un formato que pueda ser guardado con h5py
data_to_save = {var: ds[var].values for var in ds.variables}

# Guarda los datos en un archivo HDF5
with h5py.File('../../../data/clean/my_data.h5', 'w') as f:
    for var, data in data_to_save.items():
        f.create_dataset(var, data=data)

# 5. Especificando atributos y compresión:
with h5py.File('../../../data/clean/my_data.h5', 'w') as f:
    for var, data in data_to_save.items():
        dset = f.create_dataset(var, data=data, compression="gzip", compression_opts=9)
        dset.attrs['description'] = 'Descripción de ' + var

# compression="gzip": Especifica el tipo de compresión.
# compression_opts=9: Nivel de compresión (9 es el máximo).
# dset.attrs['description']: Añade un atributo al dataset.


In [79]:
# 2. Cargar desde un archivo HDF:
# xarray no tiene soporte directo para HDF, pero puedes usar h5netcdf o h5py 
# para leer archivos HDF y luego convertirlos a Dataset.

# Abriendo el archivo HDF
file = h5py.File('../../../data/clean/my_data.h5', 'r')

# Aquí necesitarías convertir manualmente los grupos y datasets HDF a xarray DataArrays y Datasets
# El proceso exacto dependerá de la estructura de tu archivo HDF

# No olvides cerrar el archivo cuando hayas terminado
file.close()


Conclusión

Crear DataArray y Dataset desde cero en xarray es un proceso directo y potente que te permite manejar datos multidimensionales de manera eficiente. Cargar datos desde formatos comunes como netCDF permite integrar xarray en flujos de trabajo existentes y aprovechar sus potentes capacidades de análisis y visualización. A medida que te familiarices con estas estructuras, descubrirás formas cada vez más complejas y efectivas de manipular y analizar tus datos.

# Indexación y Selección

xarray ofrece formas potentes y flexibles de indexar y seleccionar datos, aprovechando tanto métodos similares a NumPy como avanzadas capacidades basadas en etiquetas y nombres de dimensiones.

## Básica: Similar a NumPy.

Indexación Básica: Similar a NumPy
Al igual que en NumPy, puedes usar índices basados en números enteros y slices para seleccionar datos de DataArray y Dataset.

### Indexación con Números Enteros y Slices


In [80]:
# Creando un DataArray simple
data = np.random.rand(4, 5)
dims = ['x', 'y']
coords = {'x': [10, 20, 30, 40], 'y': [1, 2, 3, 4, 5]}
da = xr.DataArray(data, dims=dims, coords=coords)

# Selección de un elemento específico
print(da[1, 3])

# Selección de una subsección usando slices
print(da[1:3, 2:5])


<xarray.DataArray ()>
array(0.58991474)
Coordinates:
    x        int32 20
    y        int32 4
<xarray.DataArray (x: 2, y: 3)>
array([[0.24547432, 0.58991474, 0.17459826],
       [0.45122111, 0.3308928 , 0.17414847]])
Coordinates:
  * x        (x) int32 20 30
  * y        (y) int32 3 4 5


### Indexación Booleana:

Puedes usar arrays de booleanos para seleccionar datos basados en condiciones.

In [83]:
da > 0.5

<xarray.DataArray (x: 4, y: 5)>
array([[False,  True,  True, False, False],
       [False, False, False,  True, False],
       [False,  True, False, False, False],
       [ True, False,  True,  True, False]])
Coordinates:
  * x        (x) int32 10 20 30 40
  * y        (y) int32 1 2 3 4 5

In [88]:
# Seleccionar elementos donde el valor es mayor que 0.5
# Usando .where() para seleccionar elementos mayores que 0.5
filtered_da = da.where(da > 0.5)

print(filtered_da)

<xarray.DataArray (x: 4, y: 5)>
array([[       nan, 0.84147374, 0.71130198,        nan,        nan],
       [       nan,        nan,        nan, 0.58991474,        nan],
       [       nan, 0.53708758,        nan,        nan,        nan],
       [0.8401459 ,        nan, 0.82453839, 0.86469037,        nan]])
Coordinates:
  * x        (x) int32 10 20 30 40
  * y        (y) int32 1 2 3 4 5


In [90]:
# Eliminando los NaN y aplanando el DataArray resultante
non_nan_values = filtered_da.dropna(dim='x', how='all').values.flatten()

# Filtrando los NaN de la matriz aplanada
non_nan_values = non_nan_values[~np.isnan(non_nan_values)]

print(non_nan_values)


[0.84147374 0.71130198 0.58991474 0.53708758 0.8401459  0.82453839
 0.86469037]


## Avanzada: Uso de etiquetas y nombres de dimensiones.

xarray brilla en su capacidad para seleccionar datos utilizando etiquetas y nombres de dimensiones, lo que hace que el acceso a los datos sea más intuitivo y menos propenso a errores.

### Selección por Etiquetas con .loc:

In [84]:
# Seleccionar datos por etiquetas de coordenadas
print(da.loc[20:30, 2:4])

<xarray.DataArray (x: 2, y: 3)>
array([[0.34098685, 0.24547432, 0.58991474],
       [0.53708758, 0.45122111, 0.3308928 ]])
Coordinates:
  * x        (x) int32 20 30
  * y        (y) int32 2 3 4


### Selección por Nombre de Dimensión con .sel:

In [85]:
# Seleccionar datos usando nombres de dimensiones y valores de coordenadas
print(da.sel(x=20, y=5))

<xarray.DataArray ()>
array(0.17459826)
Coordinates:
    x        int32 20
    y        int32 5


In [86]:
# Puedes usar slices y listas de etiquetas en .sel también:
print(da.sel(x=slice(20, 30), y=[2, 4, 5]))

<xarray.DataArray (x: 2, y: 3)>
array([[0.34098685, 0.58991474, 0.17459826],
       [0.53708758, 0.3308928 , 0.17414847]])
Coordinates:
  * x        (x) int32 20 30
  * y        (y) int32 2 4 5


###  Selección por Posición con .isel:

Mientras que .sel utiliza etiquetas, .isel te permite seleccionar datos por índices numéricos, pero manteniendo el uso de nombres de dimensiones.

In [87]:
# Seleccionar datos por índices de posición
print(da.isel(x=0, y=slice(1, 4)))

<xarray.DataArray (y: 3)>
array([0.84147374, 0.71130198, 0.08312456])
Coordinates:
    x        int32 10
  * y        (y) int32 2 3 4


### Consejos y Trucos

+ Combinación de Métodos: Puedes combinar diferentes métodos de indexación y selección para lograr el acceso deseado a los datos.
+ Alineación Automática: Al realizar operaciones entre DataArray y Dataset, xarray alinea automáticamente las dimensiones basadas en etiquetas, lo que puede evitar muchos errores comunes.
+ Metadatos Conservados: Al seleccionar y manipular datos, xarray intenta conservar los metadatos asociados, lo que facilita el seguimiento de la información sobre tus datos.

### Conclusión

La indexación y selección en xarray es flexible y poderosa, ofreciendo métodos intuitivos y seguros para manipular y acceder a tus datos multidimensionales. Aprovechar las capacidades de indexación basada en etiquetas y nombres de dimensiones puede hacer que tu código sea más legible y menos propenso a errores, especialmente cuando trabajas con conjuntos de datos complejos o grandes.


# Trabajando con Dimensiones

xarray se destaca por su capacidad para trabajar con dimensiones nombradas, lo que permite un análisis más intuitivo y eficiente. Además, la alineación automática basada en etiquetas facilita las operaciones entre objetos DataArray y Dataset que comparten dimensiones comunes.

## Entender y trabajar con dimensiones nombradas.

En xarray, cada dimensión de un DataArray o Dataset tiene un nombre. Esto es poderoso porque te permite referenciar y operar en los datos por su nombre significativo en lugar de depender solo de su posición.

### Crear y Manipular Dimensiones Nombradas:

Al crear un DataArray o Dataset, especificas los nombres de las dimensiones, lo que luego puedes utilizar para manipular los datos.


In [91]:
import pandas as pd

# Creando un DataArray con dimensiones nombradas
temps = np.random.rand(3, 4)
times = pd.date_range("20230101", periods=3)
locs = ['North', 'East', 'South', 'West']

temperature = xr.DataArray(temps, coords=[times, locs], dims=['time', 'location'])
print(temperature)


<xarray.DataArray (time: 3, location: 4)>
array([[0.27552192, 0.86589479, 0.62281034, 0.28225857],
       [0.1032504 , 0.66412275, 0.50109504, 0.15073642],
       [0.06896397, 0.39829573, 0.92814056, 0.34015985]])
Coordinates:
  * time      (time) datetime64[ns] 2023-01-01 2023-01-02 2023-01-03
  * location  (location) <U5 'North' 'East' 'South' 'West'




## Alineación automática basada en etiquetas.

# Computación - Regresión lineal

In [8]:
# Supongamos que tenemos datos de ejemplo en un DataArray de xarray
# Dimensiones: 'grupo' para identificar cada grupo, 'observacion' para las observaciones de cada grupo
# Variables: 'x1' y 'x2' son los predictores, 'y' es la variable dependiente

# Generar datos de ejemplo
np.random.seed(0)
n_grupos = 12
n_observaciones = 109
x1 = np.random.rand(n_grupos, n_observaciones)
x2 = np.random.rand(n_grupos, n_observaciones)
y = 2.5 * x1 - 1.5 * x2 + np.random.randn(n_grupos, n_observaciones) * 0.1  # y es una combinación lineal de x1 y x2 con ruido

datos = xr.Dataset({
    'x1': (('grupo', 'observacion'), x1),
    'x2': (('grupo', 'observacion'), x2),
    'y': (('grupo', 'observacion'), y)
}, coords={'grupo': np.arange(n_grupos), 'observacion': np.arange(n_observaciones)})

# Agregar una columna de unos para el intercepto
datos['intercepto'] = xr.DataArray(np.ones((n_grupos, n_observaciones)), dims=('grupo', 'observacion'))

datos


<xarray.Dataset>
Dimensions:      (grupo: 12, observacion: 109)
Coordinates:
  * grupo        (grupo) int32 0 1 2 3 4 5 6 7 8 9 10 11
  * observacion  (observacion) int32 0 1 2 3 4 5 6 ... 103 104 105 106 107 108
Data variables:
    x1           (grupo, observacion) float64 0.5488 0.7152 ... 0.6211 0.09781
    x2           (grupo, observacion) float64 0.8844 0.7692 ... 0.8452 0.4554
    y            (grupo, observacion) float64 0.03568 0.5456 ... 0.2746 -0.3505
    intercepto   (grupo, observacion) float64 1.0 1.0 1.0 1.0 ... 1.0 1.0 1.0

In [9]:
# Preparar la matriz X y el vector y para cada grupo
X = datos.to_array(dim='variable').sel(variable=['intercepto', 'x1', 'x2']).transpose('grupo', 'observacion', 'variable')
y = datos['y']

X.coords

Coordinates:
  * grupo        (grupo) int32 0 1 2 3 4 5 6 7 8 9 10 11
  * observacion  (observacion) int32 0 1 2 3 4 5 6 ... 103 104 105 106 107 108
  * variable     (variable) object 'intercepto' 'x1' 'x2'

In [10]:
y.coords

Coordinates:
  * grupo        (grupo) int32 0 1 2 3 4 5 6 7 8 9 10 11
  * observacion  (observacion) int32 0 1 2 3 4 5 6 ... 103 104 105 106 107 108

In [11]:
# Resolver la regresión lineal para cada grupo usando la ecuación normal
# Nota: Se aplica un pequeño valor a la diagonal de X^T X para evitar problemas de singularidad
coeficientes = xr.apply_ufunc(
    lambda x, y: np.linalg.inv(x.T @ x + np.eye(x.shape[1]) * 1e-5) @ x.T @ y, 
    X, y,
    input_core_dims=[['observacion', 'variable'], ['observacion']],
    output_core_dims=[['variable']],
    vectorize=True  # Esto permite aplicar la función a cada grupo
)

# coeficientes tendrá una dimensión 'grupo' y 'variable', donde 'variable' incluye el intercepto, x1 y x2
print(coeficientes)


<xarray.DataArray (grupo: 12, variable: 3)>
array([[ 1.91078762e-02,  2.50447403e+00, -1.51585249e+00],
       [-2.57470073e-02,  2.47866706e+00, -1.46512960e+00],
       [-6.99193403e-03,  2.52535053e+00, -1.50957963e+00],
       [-7.21054589e-03,  2.52362279e+00, -1.51226253e+00],
       [ 3.18941788e-04,  2.47986283e+00, -1.48951026e+00],
       [ 1.65556033e-02,  2.50109288e+00, -1.54026876e+00],
       [-1.72182658e-02,  2.48029719e+00, -1.47335866e+00],
       [ 4.14802577e-02,  2.43900294e+00, -1.51441347e+00],
       [-1.40214465e-02,  2.46033707e+00, -1.46826539e+00],
       [-5.30224450e-03,  2.50725613e+00, -1.51785704e+00],
       [-1.23581433e-02,  2.51234182e+00, -1.50881662e+00],
       [ 1.90972716e-03,  2.50343176e+00, -1.51373473e+00]])
Coordinates:
  * grupo     (grupo) int32 0 1 2 3 4 5 6 7 8 9 10 11
  * variable  (variable) object 'intercepto' 'x1' 'x2'
